# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_prj1.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Test_Prj1(object):
    def setupUi(self, Test_Prj1):
        Test_Prj1.setObjectName("Test_Prj1")
        Test_Prj1.resize(1259, 663)
        self.pB_exit = QtWidgets.QPushButton(Test_Prj1)
        self.pB_exit.setEnabled(True)
        self.pB_exit.setGeometry(QtCore.QRect(10, 630, 75, 23))
        self.pB_exit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pB_exit.setObjectName("pB_exit")
        self.tE_log = QtWidgets.QTextEdit(Test_Prj1)
        self.tE_log.setGeometry(QtCore.QRect(220, 20, 321, 591))
        self.tE_log.setFrameShape(QtWidgets.QFrame.Box)
        self.tE_log.setLineWidth(1)
        self.tE_log.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.tE_log.setObjectName("tE_log")
        self.pB_clear = QtWidgets.QPushButton(Test_Prj1)
        self.pB_clear.setGeometry(QtCore.QRect(110, 630, 75, 23))
        self.pB_clear.setObjectName("pB_clear")
        self.gB_udpserver = QtWidgets.QGroupBox(Test_Prj1)
        self.gB_udpserver.setGeometry(QtCore.QRect(10, 260, 191, 131))
        self.gB_udpserver.setObjectName("gB_udpserver")
        self.tL_port = QtWidgets.QLabel(self.gB_udpserver)
        self.tL_port.setGeometry(QtCore.QRect(10, 60, 31, 16))
        self.tL_port.setObjectName("tL_port")
        self.lE_port = QtWidgets.QLineEdit(self.gB_udpserver)
        self.lE_port.setGeometry(QtCore.QRect(50, 60, 131, 20))
        self.lE_port.setObjectName("lE_port")
        self.cB_ip = QtWidgets.QComboBox(self.gB_udpserver)
        self.cB_ip.setGeometry(QtCore.QRect(50, 20, 131, 22))
        self.cB_ip.setEditable(False)
        self.cB_ip.setCurrentText("")
        self.cB_ip.setObjectName("cB_ip")
        self.pB_udpbegin = QtWidgets.QPushButton(self.gB_udpserver)
        self.pB_udpbegin.setGeometry(QtCore.QRect(90, 100, 75, 23))
        self.pB_udpbegin.setObjectName("pB_udpbegin")
        self.tL_ip = QtWidgets.QLabel(self.gB_udpserver)
        self.tL_ip.setGeometry(QtCore.QRect(10, 20, 21, 16))
        self.tL_ip.setObjectName("tL_ip")
        self.gB_udpclient = QtWidgets.QGroupBox(Test_Prj1)
        self.gB_udpclient.setGeometry(QtCore.QRect(10, 10, 191, 241))
        self.gB_udpclient.setObjectName("gB_udpclient")
        self.cB_ip_2 = QtWidgets.QComboBox(self.gB_udpclient)
        self.cB_ip_2.setEnabled(True)
        self.cB_ip_2.setGeometry(QtCore.QRect(50, 20, 131, 22))
        self.cB_ip_2.setEditable(True)
        self.cB_ip_2.setCurrentText("")
        self.cB_ip_2.setDuplicatesEnabled(False)
        self.cB_ip_2.setObjectName("cB_ip_2")
        self.lE_port_2 = QtWidgets.QLineEdit(self.gB_udpclient)
        self.lE_port_2.setGeometry(QtCore.QRect(50, 60, 131, 20))
        self.lE_port_2.setObjectName("lE_port_2")
        self.tL_ip_2 = QtWidgets.QLabel(self.gB_udpclient)
        self.tL_ip_2.setGeometry(QtCore.QRect(10, 12, 21, 20))
        self.tL_ip_2.setObjectName("tL_ip_2")
        self.tL_port_2 = QtWidgets.QLabel(self.gB_udpclient)
        self.tL_port_2.setGeometry(QtCore.QRect(10, 60, 31, 16))
        self.tL_port_2.setObjectName("tL_port_2")
        self.rB_byte = QtWidgets.QRadioButton(self.gB_udpclient)
        self.rB_byte.setGeometry(QtCore.QRect(100, 90, 89, 16))
        self.rB_byte.setObjectName("rB_byte")
        self.rB_string = QtWidgets.QRadioButton(self.gB_udpclient)
        self.rB_string.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.rB_string.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rB_string.setChecked(True)
        self.rB_string.setObjectName("rB_string")
        self.cB_order = QtWidgets.QComboBox(self.gB_udpclient)
        self.cB_order.setGeometry(QtCore.QRect(20, 180, 151, 22))
        self.cB_order.setEditable(True)
        self.cB_order.setCurrentText("")
        self.cB_order.setObjectName("cB_order")
        self.tE_send = QtWidgets.QTextEdit(self.gB_udpclient)
        self.tE_send.setGeometry(QtCore.QRect(20, 120, 151, 51))
        self.tE_send.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.tE_send.setObjectName("tE_send")
        self.pB_send = QtWidgets.QPushButton(self.gB_udpclient)
        self.pB_send.setGeometry(QtCore.QRect(100, 210, 71, 23))
        self.pB_send.setObjectName("pB_send")
        self.chB_masterip = QtWidgets.QCheckBox(self.gB_udpclient)
        self.chB_masterip.setGeometry(QtCore.QRect(20, 210, 91, 19))
        self.chB_masterip.setObjectName("chB_masterip")
        self.lE_incnt = QtWidgets.QLineEdit(Test_Prj1)
        self.lE_incnt.setGeometry(QtCore.QRect(320, 510, 42, 20))
        self.lE_incnt.setObjectName("lE_incnt")
        self.tL_incnt = QtWidgets.QLabel(Test_Prj1)
        self.tL_incnt.setGeometry(QtCore.QRect(235, 513, 71, 16))
        self.tL_incnt.setObjectName("tL_incnt")
        self.tL_outcnt = QtWidgets.QLabel(Test_Prj1)
        self.tL_outcnt.setGeometry(QtCore.QRect(235, 543, 71, 16))
        self.tL_outcnt.setObjectName("tL_outcnt")
        self.lE_outcnt = QtWidgets.QLineEdit(Test_Prj1)
        self.lE_outcnt.setGeometry(QtCore.QRect(320, 540, 41, 20))
        self.lE_outcnt.setObjectName("lE_outcnt")
        self.tB_log = QtWidgets.QTextBrowser(Test_Prj1)
        self.tB_log.setGeometry(QtCore.QRect(210, 20, 391, 631))
        self.tB_log.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.tB_log.setMouseTracking(False)
        self.tB_log.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tB_log.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tB_log.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.tB_log.setTabChangesFocus(False)
        self.tB_log.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.tB_log.setAcceptRichText(False)
        self.tB_log.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextSelectableByMouse)
        self.tB_log.setObjectName("tB_log")
        self.tB_log_2 = QtWidgets.QTextBrowser(Test_Prj1)
        self.tB_log_2.setGeometry(QtCore.QRect(610, 20, 641, 631))
        self.tB_log_2.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.tB_log_2.setMouseTracking(False)
        self.tB_log_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tB_log_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tB_log_2.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.tB_log_2.setTabChangesFocus(False)
        self.tB_log_2.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.tB_log_2.setAcceptRichText(False)
        self.tB_log_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextSelectableByMouse)
        self.tB_log_2.setObjectName("tB_log_2")
        self.tL_txmac = QtWidgets.QLabel(Test_Prj1)
        self.tL_txmac.setGeometry(QtCore.QRect(20, 390, 72, 15))
        self.tL_txmac.setObjectName("tL_txmac")
        self.cB_txmac = QtWidgets.QComboBox(Test_Prj1)
        self.cB_txmac.setGeometry(QtCore.QRect(20, 410, 161, 22))
        self.cB_txmac.setObjectName("cB_txmac")
        self.pB_udpbegin_2 = QtWidgets.QPushButton(Test_Prj1)
        self.pB_udpbegin_2.setGeometry(QtCore.QRect(290, 160, 75, 23))
        self.pB_udpbegin_2.setObjectName("pB_udpbegin_2")
        self.chB_allip = QtWidgets.QCheckBox(Test_Prj1)
        self.chB_allip.setGeometry(QtCore.QRect(280, 100, 71, 16))
        self.chB_allip.setObjectName("chB_allip")
        self.groupBox = QtWidgets.QGroupBox(Test_Prj1)
        self.groupBox.setGeometry(QtCore.QRect(10, 440, 181, 171))
        self.groupBox.setObjectName("groupBox")
        self.pB_avetime = QtWidgets.QPushButton(self.groupBox)
        self.pB_avetime.setGeometry(QtCore.QRect(60, 130, 93, 28))
        self.pB_avetime.setObjectName("pB_avetime")
        self.lE_avetime = QtWidgets.QLineEdit(self.groupBox)
        self.lE_avetime.setGeometry(QtCore.QRect(70, 60, 81, 21))
        self.lE_avetime.setObjectName("lE_avetime")
        self.tL_avetime = QtWidgets.QLabel(self.groupBox)
        self.tL_avetime.setGeometry(QtCore.QRect(20, 60, 41, 16))
        self.tL_avetime.setObjectName("tL_avetime")
        self.tL_avetime_2 = QtWidgets.QLabel(self.groupBox)
        self.tL_avetime_2.setGeometry(QtCore.QRect(10, 100, 51, 16))
        self.tL_avetime_2.setObjectName("tL_avetime_2")
        self.lE_avetime_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lE_avetime_2.setGeometry(QtCore.QRect(70, 100, 81, 21))
        self.lE_avetime_2.setObjectName("lE_avetime_2")
        self.tL_avenum = QtWidgets.QLabel(self.groupBox)
        self.tL_avenum.setGeometry(QtCore.QRect(10, 20, 51, 20))
        self.tL_avenum.setObjectName("tL_avenum")
        self.lE_avenum = QtWidgets.QLineEdit(self.groupBox)
        self.lE_avenum.setGeometry(QtCore.QRect(70, 20, 81, 21))
        self.lE_avenum.setObjectName("lE_avenum")
        self.gB_udpserver.raise_()
        self.pB_exit.raise_()
        self.tE_log.raise_()
        self.pB_clear.raise_()
        self.gB_udpclient.raise_()
        self.lE_incnt.raise_()
        self.tL_incnt.raise_()
        self.tL_outcnt.raise_()
        self.lE_outcnt.raise_()
        self.tB_log_2.raise_()
        self.tL_txmac.raise_()
        self.cB_txmac.raise_()
        self.pB_udpbegin_2.raise_()
        self.chB_allip.raise_()
        self.tB_log.raise_()
        self.groupBox.raise_()

        self.retranslateUi(Test_Prj1)
        self.cB_ip.setCurrentIndex(-1)
        self.cB_ip_2.setCurrentIndex(-1)
        self.cB_order.setCurrentIndex(-1)
        self.pB_exit.clicked.connect(Test_Prj1.close)
        self.pB_clear.clicked.connect(Test_Prj1.clearLog)
        self.cB_ip_2.editTextChanged['QString'].connect(Test_Prj1.autoComp)
        self.pB_udpbegin_2.clicked.connect(Test_Prj1.udpSet)
        self.pB_udpbegin.clicked.connect(Test_Prj1.udpBegin)
        self.tE_log.textChanged.connect(Test_Prj1.cntUpdated)
        self.pB_send.clicked.connect(Test_Prj1.udpSend)
        self.cB_order.activated['QString'].connect(Test_Prj1.udpOrder)
        self.pB_avetime.clicked.connect(Test_Prj1.uwbAveTime)
        self.chB_masterip.toggled['bool'].connect(Test_Prj1.masterIP)
        QtCore.QMetaObject.connectSlotsByName(Test_Prj1)

    def retranslateUi(self, Test_Prj1):
        _translate = QtCore.QCoreApplication.translate
        Test_Prj1.setWindowTitle(_translate("Test_Prj1", "程序烧写控制器"))
        self.pB_exit.setText(_translate("Test_Prj1", "退出"))
        self.pB_clear.setText(_translate("Test_Prj1", "清空日志"))
        self.gB_udpserver.setTitle(_translate("Test_Prj1", "UDP服务器"))
        self.tL_port.setText(_translate("Test_Prj1", "port"))
        self.lE_port.setText(_translate("Test_Prj1", "9999"))
        self.pB_udpbegin.setText(_translate("Test_Prj1", "udp启动"))
        self.tL_ip.setText(_translate("Test_Prj1", "ip"))
        self.gB_udpclient.setTitle(_translate("Test_Prj1", "UDP客户端"))
        self.lE_port_2.setText(_translate("Test_Prj1", "9999"))
        self.tL_ip_2.setText(_translate("Test_Prj1", "ip"))
        self.tL_port_2.setText(_translate("Test_Prj1", "port"))
        self.rB_byte.setText(_translate("Test_Prj1", "16进制"))
        self.rB_string.setText(_translate("Test_Prj1", "字符串"))
        self.pB_send.setText(_translate("Test_Prj1", "发送"))
        self.chB_masterip.setText(_translate("Test_Prj1", "主基站"))
        self.lE_incnt.setText(_translate("Test_Prj1", "9999"))
        self.tL_incnt.setText(_translate("Test_Prj1", "入库计数器："))
        self.tL_outcnt.setText(_translate("Test_Prj1", "出库计数器："))
        self.lE_outcnt.setText(_translate("Test_Prj1", "9999"))
        self.tL_txmac.setText(_translate("Test_Prj1", "发送MAC"))
        self.pB_udpbegin_2.setText(_translate("Test_Prj1", "udp设置"))
        self.chB_allip.setText(_translate("Test_Prj1", "全部"))
        self.groupBox.setTitle(_translate("Test_Prj1", "UWB距离精度"))
        self.pB_avetime.setText(_translate("Test_Prj1", "开始统计"))
        self.tL_avetime.setText(_translate("Test_Prj1", "均值"))
        self.tL_avetime_2.setText(_translate("Test_Prj1", "标准差"))
        self.tL_avenum.setText(_translate("Test_Prj1", "数据量"))

